config/routes.rb
Rails.application.routes.draw do

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    task = Task.find(params[:id])
    task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body bgcolor="orange">

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |t| %>
  <%= t.text_field :name, :placeholder => "Modifier le nom de la tache" %>
  <%= t.text_field :content, :placeholder => "Modifier le contenu de la tache" %>
  <%= t.submit "Edit your task" %>
<% end %>

app/views/tasks/index.html.erb
<h1>Here your Tasks</h1>
<p><% @tasks.each do |task| %></p>
<p>Nom de la tache : <%= task.name %></p>
<p>Contenu de la tache : <%= task.content %></p>
<%= link_to "Edit", edit_task_path(task) %>
<%= link_to "Delete", task_path(task), method: :delete %>
<hr>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |t| %>
  <%= t.text_field :name, :placeholder => "Contenu de votre tache" %>
  <%= t.text_field :content, :placeholder => "Contenu de votre tache" %>
  <%= t.submit "Create a new task" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Here your task number  <%= @task.id %></h1>


<ul>
  <li>Nom de la tache : <%= @task.name %></li>
  <li>Contenu de la tache : <%= @task.content %></li>
</ul>